### ISSUE TITLE
List -> table with images

### ISSUE THREAD

**Issue by ozkriff** [ozkriff/awesome-quads#9]
Is it a good idea to convert the list formatting into tables and add a column for images? Or maybe there's a better way to add some projects' images to the readme

**Comment by optozorax** [comment]
Tetra has a nice [showcase](https://tetra.seventeencups.net/showcase/) section on their website. I believe we could steal that idea.

**Comment by ozkriff** [comment]
On the other hand, the https://macroquad.rs exists now and it might be better to migrate awesome-quads there instead of keeping it as a separate repo.
